resources:
  - name: vluks
    icon: github
    type: git
    source: &vluks
      uri: https://github.com/SapphicCode/vluks.git
      branch: mistress

  - name: vluks-versions
    icon: github
    type: git
    source:
      <<: *vluks
      fetch_tags: yes
      tag_filter: v*

jobs:
  - name: nightly
    plan:
      - get: vluks
        trigger: yes
      - task: build
        config:
          inputs:
            - name: vluks
              path: .
          outputs:
            - name: build
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker.io/library/golang
              tag: alpine
          run:
            path: go
            args:
              - build
              - -o=build
              - ./cmd/...

  - name: release
    plan:
      - get: vluks-versions
        trigger: yes
      - task: goreleaser
        config:
          inputs:
            - name: vluks-versions
              path: .
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: docker.io/goreleaser/goreleaser
          params:
            GITHUB_TOKEN: ((cassandra/github.token))
            AWS_ACCESS_KEY_ID: ((cassandra/backblaze.id))
            AWS_SECRET_ACCESS_KEY: ((cassandra/backblaze.key))
          run:
            path: goreleaser
            args:
              - release
